### ISSUE TITLE
Write prompts

### ISSUE THREAD

**Issue by g105b** [g105b/CinemaTimeMachine#6]
Prompts will be fired at random intervals, we need a minimum of three written to start.
1. The top grossing film of XXXX is YYYY.
2. The most popular genre of film in XXX is YYYY - what's your favourite XXXX film?
3. XXXX starred in Y films over the last 25 years! What's your favourite XXXX film?

If you could write these prompts with actual default details, then we can use them straight away. When they are put into HTML we can make the content dynamic by wrapping the XXX YYY bits with special tags.

Write the prompts as comments here if you like, to get us going.

**Comment by clarkcx** [comment]
# Prompt screens
1. The top grossing film of 2008 was The Dark Knight. What's your favourite comic book movie? Text the title to 07800 005563. Start your message with a film title and then tell us why you loved it!
2. Frozen is the most popular animated movie of the past 25 years. What's your favourite animation? Let us know by texting its title followed by a short message to 07800 005563.
3. In 1993 Sylvester Stallone battled Wesley Snipes onscreen in the terrible-yet-entertaining Demolition Man. What's your favourite bad action movie? Text the title and a short message to 07800 005563.
4. There have been literally too many RomComs in the past 25 years but which is the least-worst? Text the title and a short message to 07800 005563.
5. Adam Sandler has made films. Text the name of one and anything you remember about it to 07800 005563.
6. In 1991 some angry bees made everyone cry by killing Macaulay Culkin in My Girl. Which film made you super-sad in the 1990s? Text its title followed by a short message to 07800 005563.
